### ISSUE TITLE
RegDB dataset

### ISSUE THREAD

**Issue by Xiaofu233** [wangguanan/AlignGAN#2]
The RegDB dataset can not be found in the official link ’http://dm.dongguk.edu/link.html‘
Could you please share this dataset？
Thanks！

**Comment by wangguanan** [comment]
could you please leave me your e-mail?

**Comment by Xiaofu233** [comment]
> could you please leave me your e-mail?

hby0728@mail.ustc.edu.cn
Thanks a lot!

**Comment by YuPeize** [comment]
Hello, could you please share the The RegDB dataset?
My email: mg1733086@smail.nju.edu.cn
Thanks!

**Comment by wangguanan** [comment]
@YuPeize Please check your e-mail.

**Comment by YuPeize** [comment]
@wangguanan Thanks a lot!

**Comment by DTennant** [comment]
@wangguanan Hi, could you share the RegDB dataset with me?
email: zhaobc@tongji.edu.cn
Thanks

**Comment by wangguanan** [comment]
@DTennant Please check your e-mail.

**Comment by wangguanan** [comment]
If you find the RegDB useful, please kindly consider citing the official paper:

[1] D. T. Nguyen, H. G. Hong, K. W. Kim, and K. R. Park. Person recognition system based on a combination of body images from visible light and thermal cameras. Sensors, 17(3):605, 2017.

**Comment by zhouhang3** [comment]
Hello, could you please share the The RegDB dataset?
My email: hlzhouhang@163.com
Thank you!
🤭

**Comment by Panpanpie** [comment]
Could you please share me the RegDB dataset ?
email 2437006585@qq.com
Thank you very much~(∩_∩)

**Comment by zhangleilei0125** [comment]
Hello, could you please share me the RegDB dataset ?
Email：zhangleilei0125@buaa.edu.cn
Thank you very much.

**Comment by hansonchen1996** [comment]
Hello, could you please share the RegDB dataset ?
Email：chenyehansen@cug.edu.cn
Thanks a lot.

**Comment by wangguanan** [comment]
Please see the google drive link, thanks.
https://drive.google.com/file/d/1W_r7HTlitFBElaBN7QlQ3DIJYFP30Duz/view?usp=sharing

**Comment by zhangleilei0125** [comment]
Thank you
















At 2020-07-11 08:52:20, "wangguanan" <notifications@github.com> wrote:

Please see the google drive link, thanks.
https://drive.google.com/file/d/1W_r7HTlitFBElaBN7QlQ3DIJYFP30Duz/view?usp=sharing

**Comment by SCR-SCR** [comment]
Hello, could you please share the The RegDB dataset?
My email: chenyanzhi981578@163.com
Thanks!

**Comment by ZENFDEBIN** [comment]
Hello, could you please share the The RegDB dataset?
My email: zdb020316@163.com

Thanks!

**Comment by shengxun-wei** [comment]
Hello, could you please share the The RegDB dataset?
My email: wei_shengxun@163.com
Thanks!
