### ISSUE TITLE
About GPU memory

### ISSUE THREAD

**Issue by YuPeize** [wangguanan/AlignGAN#3]
Thanks for your code.
Can I achieve the best result by trainging the model with less than 40G GPU memory(single GPU)?

**Comment by wangguanan** [comment]
This code requires at least 3-4 GPUS. Thus we didn't conduct experiments with a single GPU. Sorry about that.

**Comment by wangguanan** [comment]
You can refer to this question.
A colleague trained our model with two GPUS (total 32GB), and also achieve a satisfying performance.
the issue https://github.com/wangguanan/AlignGAN/issues/4

**Comment by YuPeize** [comment]
Thanks！
