### ISSUE TITLE
Where are CMC and mAP values?

### ISSUE THREAD

**Issue by heerduo** [wangguanan/AlignGAN#4]
Time: 2019-12-04 13:19:29, indoor,multi, [array([0.56480978, 0.70538949, 0.77939312, 0.82884964, 0.86299819,
       0.88858696, 0.90806159, 0.92327899, 0.93374094, 0.9423913 ,
       0.94981884, 0.95425725, 0.95819746, 0.96259058, 0.96576087,
       0.96893116, 0.97201087, 0.97423007, 0.97653986, 0.97817029,
       0.98025362, 0.98201993, 0.98374094, 0.98532609, 0.98682065,
       0.98817935, 0.98976449, 0.9910779 , 0.99221014, 0.99311594,
       0.99397645, 0.99451993, 0.9951087 , 0.99560688, 0.99624094,
       0.99660326, 0.99701087, 0.99737319, 0.99769022, 0.99787138,
       0.99809783, 0.9982337 , 0.99850543, 0.9986413 , 0.99877717,
       0.99877717, 0.99886775, 0.99895833, 0.9990942 , 0.99932065,
       0.99950181, 0.9995471 , 0.99959239, 0.99977355, 0.99995471,
       1.        ]), 0.45644451754835486]

Thank for your work. I got this and the code stopped. Where are CMC and mAP values?  I don't know if it's related to that I use two GPU with 32G memory and CPU with 24.0.

**Comment by heerduo** [comment]
I used 4 GPU with memory 64G and CPU 20, there also exists this problem.

**Comment by wangguanan** [comment]
Hello, it is not a problem, it is the final results.
the first list is the CMC score, that is rank-1, rank-2 and so on.
The final value is mAP score.
As shown in your results, under indoor-search&multi-shot setting, the rank-1 score is 0.564, the mAP score is 0.456.
