### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by dcp15** [wangguanan/AlignGAN#6]
Can you detail the Baseline in the paper "RGB-Infrared Cross-Modality Person Re-Identification via Joint Pixel and Feature Alignment"? If you can give more about the  Hyper-parameter settings， I would appreciate it.

**Comment by wangguanan** [comment]
We use IDE model as our baseline.
Most parameters refer our another repo by setting part_num=1: 
https://github.com/wangguanan/Pytorch-Person-ReID-Baseline-PCB-Beyond-Part-Models
