### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by AI4Math-ShanZhang** [wangguanan/AlignGAN#7]
hello, the link you provided is not work, so can you uplode the model to baidudisk? By the way, could you share the RegDB dataset with me?
email: 741352743@qq.com
Thanks

**Comment by wangguanan** [comment]
Maybe you need a VPN to visit a google drive link.
We will add a baidudisk link later.

**Comment by wangguanan** [comment]
The pre-trained models have been uploaded to baidu disk:
link: https://pan.baidu.com/s/18wntdVOvjyUHBA-9C0cJBg
pwd: zsr8
