### ISSUE TITLE
RegDB dataset

### ISSUE THREAD

**Issue by YYedward** [wangguanan/AlignGAN#8]
Hello, could you please share the The RegDB dataset?
My email: jungle_hu@sjtu.edu.cn
Thanks!

**Comment by wangguanan** [comment]
Hi, please check your email.

**Comment by YYedward** [comment]
Thanks a lot.

**Comment by Panpanpie** [comment]
Excuse me, I can't find the public version RegDB dataset, I want to know that can I use it in my research just citing the official paper (I'm worried about copyright）?
